accounts/urls.py
from django.urls import path
from . import views

app_name ='accounts'

urlpatterns = [
    path('login',views.login , name='login'),
    path('signup',views.signup , name='signup'),
    path('profile',views.profile , name='profile'),
    path('profile/edit',views.profile_edit , name='profile_edit'),
    
]

home/urls.py
from django.conf.urls import url
from . import views


app_name='home'

urlpatterns = [
    url(r'^$' , views.allnotes , name='all_notes'),

]

notes/urls.py
from django.contrib import admin
from django.urls import include , path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('', include('home.urls',namespace='home')),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('notes/', include('notes_app.urls' ,namespace='notes' )),

    path('ckeditor/', include('ckeditor_uploader.urls')),
    #path('accounts/', include('accounts.urls' ,namespace='accounts' )),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



admin.site.site_header="Notes Admin Panel"
admin.site.site_title="Notes App Admin"
admin.site.site_index_title="Welcom To Notes App Admin Panel"

notes_app/urls.py
from django.conf.urls import url
from . import views


app_name='note_app'

urlpatterns = [
    url(r'^$' , views.all_notes , name='all_notes'),
    # url(r'^(?P<id>\d+)$' , views.detail , name='note_detail'),
    url(r'^(?P<slug>[-\w]+)/$' , views.detail , name='note_detail'),
    url(r'^add$' , views.note_add, name='add_note'),
    url(r'^(?P<slug>[-\w]+)/edit$' , views.edit , name='note_edit'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
# Create your models here.


class Profile(models.Model):
    user= models.OneToOneField(User , on_delete=models.CASCADE)
    #first_name = models.CharField( blank=True , max_length=100, null=True )
    #last_name = models.CharField(max_length=255, null=True , blank=True)
    phone_number = models.CharField(max_length=15 , null=True , blank=True)
    #img = models.ImageField(upload_to="profile-img")
    addres = models.CharField(max_length=50 , blank=True , null=True)




    def __str__(self):
        return str(self.user)


@receiver(post_save , sender=User)
def create_user_profile(sender,instance,created, **kwargs):
    if created:
        Profile.objects.create(
            user = instance
        )

home/models.py
from django.db import models

# Create your models here.

notes_app/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime
from django.utils.text import slugify
from ckeditor.fields import RichTextField
# Create your models here.

class Note(models.Model):
    user    = models.ForeignKey(User , on_delete=models.CASCADE)
    title   = models.CharField(max_length=50)
    slug    = models.SlugField(null=True , blank= True)
    content =  RichTextField()
    created = models.DateTimeField(blank=True, default=datetime.datetime.now)
    active  = models.BooleanField(default=True)
    tags    = models.CharField(blank=True, max_length=100)

    img = models.ImageField(upload_to="note-img")

    def save(self , *args , **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Note , self).save( *args , **kwargs)


    def __str__(self):
        return self.title

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields =['username','email','password1','password2']



class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username' , 'email' , 'first_name' , 'last_name']


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['phone_number' , 'addres']

notes_app/forms.py
from django import forms
from .models import Note
from ckeditor.widgets import CKEditorWidget



class NoteForm(forms.ModelForm):
    content=forms.CharField(widget=CKEditorWidget())
    class Meta:
        model = Note
        fields =['title' , 'content' , 'tags']

accounts/views.py
from django.shortcuts import render , redirect
from .models import Profile
from .forms import SignupForm , UserForm ,ProfileForm
from django.contrib.auth import authenticate , login


# Create your views here.



def signup(request):
    if request.method == 'POST': ##save
        form =SignupForm(request.POST)

        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']

            user = authenticate(username=username , password=password)
            login(request , user)
            return redirect('/notes')

    else: ##Show
        form = SignupForm()

    return render(request,'registration/signup.html',{'form':form})


def profile(request):
    profile = Profile.objects.get(user=request.user)
    return render(request,'profile/profile.html',{'profile':profile})




def profile_edit(request):
    profile =  Profile.objects.get(user=request.user)
    if request.method =='POST':
        userform = UserForm(request.POST , instance=request.user)
        profile_form = ProfileForm(request.POST , instance=profile)
        if userform.is_valid() and profile_form.is_valid():
            userform.save()
            myform = profile_form.save(commit=False)
            myform.user = request.user
            myform.save()
            return redirect('/accounts/profile')

    else:
        userform = UserForm(instance=request.user)
        profile_form = ProfileForm(instance=profile)

    return render(request,'profile/profile_edit.html',{
    'userform' : userform ,
    'profileform' : profile_form ,
    })

home/views.py
from django.shortcuts import render

# Create your views here.
from notes_app.models import Note



def allnotes(request):
    notes = Note.objects.all()

    return render(request , 'home.html' , {'all_notes' : notes})

notes_app/views.py
from django.shortcuts import render , redirect , get_object_or_404
from django.http import HttpResponse
from django.contrib.auth.models import User
# Create your views here.
from .models import Note
from .forms import NoteForm


## show all notes
def all_notes(request):
    user = request.user
    all_notes =Note.objects.filter(user=user)
    context = {
        'all_notes' : all_notes
    }
    return render(request , 'notes.html' , context)



## show one note
def detail(request , slug):
    note = Note.objects.get(slug=slug)
    context = {
    'note' : note
    }
    return render(request,'one_note.html' , context)




def note_add(request):
    if request.method == 'POST':
        form = NoteForm(request.POST)
        if form.is_valid():
            new_form = form.save(commit=False)
            new_form.user = request.user
            new_form.save()
            return redirect('/notes')

    else:
        form = NoteForm()

    context = {
        'form' : form ,
    }
    return render(request , 'add.html' ,context)



def edit(request , slug):
    note = get_object_or_404(Note , slug=slug)

    if request.method == 'POST':
        form = NoteForm(request.POST , instance = note)
        if form.is_valid():
            new_form = form.save(commit=False)
            new_form.user = request.user
            new_form.save()
            return redirect('/notes')

    else:
        form = NoteForm(instance = note)

    context = {
        'form' : form ,
    }
    return render(request , 'create.html' ,context)

accounts/templates/profile/profile.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap4 %}
{% block body %}

  <h2 style="margin-top: 100px;
    margin-left: 80px;">
    {{profile.user}} </h2>


<div class="container">



  <h4>{{profile.user.email}}</h4>

  
<div class="row">
  <a href="{% url 'accounts:profile_edit'%}">Edit Profile</a>

</div>
{% endblock %}

accounts/templates/profile/profile_edit.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% load static %}

{% block body %}
<h2 style="margin-top: 69px;"">
Profile Edit</h2>
<div class="container">
  <form method='POST'>
    {% csrf_token %}

{% bootstrap_form userform %}
{% bootstrap_form profileform %}
    {% buttons %}
           <button type="submit" class="btn btn-primary">Save Changes</button>
       {% endbuttons %}
     </form>
</div>

{% endblock %}

home/templates/home.html
{% extends "base.html"%}
{% load static %}
{% block body %}



    <section class="blog-area section-gap">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-md-8 pb-30 header-text">
            <h1>Our Recent Notes</h1>
            <p>
            Create , Update And Share Your Notes Withe Otheres
            </p>
          </div>
        </div>
        <div class="row">
          {% for note in all_notes %}
          <div class="single-blog col-lg-4 col-md-4">

             {% if note.img %}
              <img class="f-img img-fluid mx-auto" src="{{note.img.url}} " alt="">

              {% else %}
              <img class="f-img img-fluid mx-auto" src="{% static 'home-static/img/no_image.jpg'%} " alt="">


              {% endif %}

            <h4>
              <a href="{% url 'notes:note_detail' note.slug %}">{{note.title}}</a>
            </h4>
            <p>
              {{note.content|safe|truncatewords:'20'}}

            </p>
            <div class="bottom d-flex justify-content-between align-items-center flex-wrap">
              <div>
                <img class="img-fluid" src="{% static 'home-static/img/user.png' %}" alt="">
                <a href="#"><span>{{note.user.username}}</span></a>
              </div>
              <div class="meta">
                {{note.created|date:"j M"}}
              </div>
            </div>
          </div>
            {% endfor %}
        </div>
      </div>
    </section>
    {% endblock%}

notes_app/templates/add.html
{% extends "base.html" %}
{% load bootstrap4 %}
{%block body%}


<<div class="row">
  <<div class="add_form">
    <form method="post">
      {% csrf_token %}
      {{ form.media }}
      {% bootstrap_form form %}
      {% buttons %}
                 <button type="submit" class="btn btn-primary">Create Note</button>
             {% endbuttons %}    </form>
  </div>
</div>

{% endblock %}

notes_app/templates/all_notes.html
<h1>Welcome In Notes App</h1>


<h3>All Available Notes</h3>
<<a href="{% url 'notes:add_note' %}"> Add New Note </a>
<br>
<hr>
{% for note in all_notes %}
<a href="{% url 'notes:note_detail' note.slug %}"> {{note}} </a>
<br>
{% endfor %}

notes_app/templates/create.html
{% extends "base.html" %}
{% load bootstrap4 %}
{%block body%}



<<div class="row">
  <<div class="add_form">
    <form method="post">
      {% csrf_token %}
      {{ form.media }}
      {% bootstrap_form form %}
          {% buttons %}
                 <button type="submit" class="btn btn-primary">Save Changes</button>
             {% endbuttons %}    </form>
  </div>
</div>





{% endblock %}

notes_app/templates/note_detail.html
<h1>{{note}}</h1>



<hr>
<<a href="{% url 'notes:note_edit' note.slug %}"> Update Note Details</a>
<hr>

<h4>{{note.content|safe}}</h4>

<h5>{{note.created}}</h5>

<h4>{{note.active}}</h4>

<h5>{{note.tags}}</h5>

notes_app/templates/notes.html
{% extends "base.html"%}
{% load static %}
{% block body %}


    <section class="blog-area section-gap">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-md-8 pb-30 header-text">
            <h1>Your Recent Notes</h1>
            <p>
            Create , Update And Share Your Notes Withe Otheres
            </p>

            <a href="{% url 'notes:add_note' %}"> Add New Note </a>

          </div>
        </div>
        <div class="row">
          {% for note in all_notes %}
          <div class="single-blog col-lg-4 col-md-4">

             {% if note.img %}
              <img class="f-img img-fluid mx-auto" src="{{note.img.url}}" alt="">

              {% else %}
              <img class="f-img img-fluid mx-auto" src="{% static 'home-static/img/no_image.jpg'%} " alt="">

              {% endif %}
            <h4>
              <a href="{% url 'notes:note_detail' note.slug %}">{{note.title}}</a>
            </h4>
            <p>
              {{note.content|safe|truncatewords:'20'}}

            </p>
            <div class="bottom d-flex justify-content-between align-items-center flex-wrap">
              <div>
                <img class="img-fluid" src="{% static 'home-static/img/user.png' %}" alt="">
                <a href="#"><span>{{note.user.username}}</span></a>
              </div>
              <div class="meta">
                {{note.created|date:"j M"}}
              </div>
            </div>
          </div>
            {% endfor %}
        </div>
      </div>
    </section>
    {% endblock%}

notes_app/templates/one_note.html
{%extends "base.html" %}
{% load static %}

{% block body %}


    <!-- Start blog Area -->
    <section class="blog-area section-gap">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-md-8 pb-30 header-text">
            <h1>{{note}}</h1>
            <p>
              {{note.created|date:"j M"}} | {{note.tags}} | {{note.user.username}}
            </p>
          </div>
        </div>
        <div class="row">
          <div class="single-blog col-lg-10 col-md-10">

            <img class="f-img img-fluid mx-auto post-banner" src="{{note.img.url}}" alt="">
            <p>
              {{note.content|safe}}
            </p>
          </div>
        </div>
      </div>
    </section>
    <!-- end blog Area -->
{% endblock%}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="zxx" class="no-js">
<head>
  <!-- Mobile Specific Meta -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Favicon-->
  <link rel="shortcut icon" href="img/fav.png">
  <!-- Author Meta -->
  <meta name="author" content="Colorlib">
  <!-- Meta Description -->
  <meta name="description" content="">
  <!-- Meta Keyword -->
  <meta name="keywords" content="">
  <!-- meta character set -->
  <meta charset="UTF-8">
  <!-- Site Title -->
  <title>Quick Notes</title>

  <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700" rel="stylesheet">
    <!--
    CSS
    ============================================= -->
    <link rel="stylesheet" href="{% static 'home-static/css/linearicons.css' %}">
    <link rel="stylesheet" href="{% static 'home-static/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'home-static/css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'home-static/css/nice-select.css' %}">
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="{% static 'home-static/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'home-static/css/main.css' %}">
    <link rel="stylesheet" href="{% static 'home-static/css/mystyle.css' %}">
  </head>
  <body>

    <!-- Start Header Area -->
    <header class="default-header">
      <div class="container">
        <div class="header-wrap">
          <div class="header-top d-flex justify-content-between align-items-center">
            <div class="logo">
              <a href="/"><img src=" {% static 'home-static/img/logo5.png' %} " style='width:28px' alt=""> Quick Notes</a>
            </div>
            <div class="main-menubar d-flex align-items-center">
              {% if user.is_authenticated %}
              <nav class="hide">
                <a href="{% url 'notes:all_notes' %}">Your Notes</a>
                <a href="{% url 'accounts:profile' %}">profile</a>
              </nav>
              {% else %}
              <nav class="hide">
                <a href="{% url 'accounts:login' %}">Login</a>
                <a href="{% url 'accounts:signup'%}">Signup</a>
              </nav>
              {% endif %}
              <div class="menu-bar"><span class="lnr lnr-menu"></span></div>
            </div>
          </div>
        </div>
      </div>
    </header>
    <!-- End Header Area -->



    <!-- Start blog Area -->
    {% block body %}

    {% endblock %}


    <!-- end blog Area -->

    <!-- start footer Area -->
    <footer class="footer-area section-gap">
      <div class="container">
        <div class="row">
          <div class="col-lg-4  col-md-6">
            <div class="single-footer-widget mail-chimp">
              <h6 class="mb-20">Contact Us</h6>
              <p>
                Saudi Arabia - Qassem
              </p>
              <h3>966-555555551</h3>
              <h3>966-555555552</h3>
            </div>
          </div>
          <div class="col-lg-6  col-md-12">
            <div class="single-footer-widget newsletter">
              <h6>Newsletter</h6>
              <p>You can trust us. we only send promo offers, not a single spam.</p>
              <div id="mc_embed_signup">
                <form target="_blank" novalidate="true" action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01" method="get" class="form-inline">

                  <div class="form-group row" style="width: 100%">
                    <div class="col-lg-8 col-md-12">
                      <input name="EMAIL" placeholder="Enter Email" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Email '" required="" type="email">
                      <div style="position: absolute; left: -5000px;">
                        <input name="b_36c4fd991d266f23781ded980_aefe40901a" tabindex="-1" value="" type="text">
                      </div>
                    </div>

                    <div class="col-lg-4 col-md-12">
                      <button class="nw-btn primary-btn">Subscribe<span class="lnr lnr-arrow-right"></span></button>
                    </div>
                  </div>
                  <div class="info"></div>
                </form>
              </div>
            </div>
          </div>
        </div>

        <div class="row footer-bottom d-flex justify-content-between">
          <p class="col-lg-8 col-sm-12 footer-text m-0">
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
          </p>
          <div class="col-lg-4 col-sm-12 footer-social">
            <a href="#"><i class="fa fa-facebook"></i></a>
            <a href="#"><i class="fa fa-twitter"></i></a>
            <a href="#"><i class="fa fa-dribbble"></i></a>
            <a href="#"><i class="fa fa-behance"></i></a>
          </div>
        </div>
      </div>
    </footer>
    <!-- End footer Area -->


    <script src="{% static 'home-static/js/vendor/jquery-2.2.4.min.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="{% static 'home-static/js/vendor/bootstrap.min.js' %}"></script>
    <script src="{% static 'home-static/js/jquery.ajaxchimp.min.js' %}"></script>
    <script src="{% static 'home-static/js/jquery.nice-select.min.js' %}"></script>
    <script src="{% static 'home-static/js/jquery.sticky.js' %}"></script>
    <script src="{% static 'home-static/js/parallax.min.js' %}"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="{% static 'home-static/js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'home-static/js/waypoints.min.js' %}"></script>
    <script src="{% static 'home-static/js/jquery.counterup.min.js' %}"></script>
    <script src="{% static 'home-static/js/main.js' %}"></script>
  </body>
</html>

templates/base_generic.html
<div>
    {% block content %}
    {% endblock %}
</div>